language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"

install:
 - pip install django==1.4.18
 - pip install -r requirements-dev.txt
 - pip install coveralls

script:
 - coverage run --source=djangomaster manage.py test

after_success:
 - coveralls
